<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ComputeInMemory.Storage\ComputeInMemory.Storage.csproj" />
    <ProjectReference Include="..\..\src\ComputeInMemory.Scheduler\ComputeInMemory.Scheduler.csproj" />
    <ProjectReference Include="..\..\src\ComputeInMemory.DataPath\ComputeInMemory.DataPath.csproj" />
    <ProjectReference Include="..\..\src\ComputeInMemory.Benchmark\ComputeInMemory.Benchmark.csproj" />
  </ItemGroup>

</Project>
